[package]
name = "xpgl"
version = "0.1.0"
authors = ["Sam Crow <samcrow@uw.edu>"]

build = "build.rs"

[lib]

[build-dependencies]
gl_generator = { version = "0.4.2", path = "../gl-rs/gl_generator" }
